version: "3.9"

services:
  web_api:
    build: .
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "TechNinjaz@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"