version: "3.9"

services:
  web_api:
    build: .
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_ENVIRONMENT: Development 
    depends_on:
      - db
      - ui
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: "localhost"
        ACCEPT_EULA: "Y"
  ui:
    image: node
  